apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: configmap-grafana_patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: grafana