---
# Source: tempo-distributed/charts/minio/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-minio
  namespace: "grafana-enterprise-traces"
  labels:
    app: minio
    chart: minio-4.0.12
    release: tempo
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
