---
# Source: tempo-distributed/charts/minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-minio
  namespace: "grafana-enterprise-traces"
  labels:
    app: minio
    chart: minio-4.0.12
    release: tempo
    heritage: Helm
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: tempo
