---
# Source: tempo-distributed/templates/configmap-tempo.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gem-tempo-config
  labels:
    helm.sh/chart: tempo-distributed-1.23.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: gem
    app.kubernetes.io/version: "2.6.0"
    app.kubernetes.io/managed-by: Helm
  namespace: "grafana-enterprise-traces"
data:
  tempo-query.yaml: |
    backend: 127.0.0.1:3100
    
  tempo.yaml: |
    
    admin_api:
      leader_election:
        enabled: true
        ring:
          kvstore:
            store: memberlist
    admin_client:
      storage:
        backend: s3
        s3:
          access_key_id: grafana-tempo
          bucket_name: enterprise-traces-admin
          endpoint: tempo-minio:9000
          insecure: true
          secret_access_key: supersecret
    auth:
      type: enterprise
    cache:
      caches:
      - memcached:
          consistent_hash: true
          host: 'gem-tempo-memcached'
          service: memcached-client
          timeout: 500ms
        roles:
        - parquet-footer
        - bloom
        - frontend-search
    compactor:
      compaction:
        block_retention: 48h
        compacted_block_retention: 1h
        compaction_cycle: 30s
        compaction_window: 1h
        max_block_bytes: 107374182400
        max_compaction_objects: 6000000
        max_time_per_tenant: 5m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
      ring:
        kvstore:
          store: memberlist
    distributor:
      log_received_spans:
        enabled: true
        filter_by_status_error: false
        include_all_attributes: false
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      ring:
        kvstore:
          store: memberlist
    gateway:
      proxy:
        admin_api:
          url: http://gem-tempo-admin-api.grafana-enterprise-traces.svc:3100
        compactor:
          url: http://gem-tempo-compactor.grafana-enterprise-traces.svc:3100
        default:
          url: http://gem-tempo-admin-api.grafana-enterprise-traces.svc:3100
        distributor:
          otlp/grpc:
            url: h2c://gem-tempo-distributor.grafana-enterprise-traces.svc:4317
          otlp/http:
            url: http://gem-tempo-distributor.grafana-enterprise-traces.svc:4318
          url: http://gem-tempo-distributor.grafana-enterprise-traces.svc:3100
        ingester:
          url: http://gem-tempo-ingester.grafana-enterprise-traces.svc:3100
        querier:
          url: http://gem-tempo-querier.grafana-enterprise-traces.svc:3100
        query_frontend:
          url: http://gem-tempo-query-frontend.grafana-enterprise-traces.svc:3100
    http_api_prefix: null
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
        tokens_file_path: /var/tempo/tokens.json
    license:
      path: /license/license.jwt
    memberlist:
      abort_if_cluster_join_fails: false
      bind_addr: []
      bind_port: 7946
      cluster_label: 'gem.grafana-enterprise-traces'
      gossip_interval: 1s
      gossip_nodes: 2
      gossip_to_dead_nodes_time: 30s
      join_members:
      - dns+gem-tempo-gossip-ring:7946
      leave_timeout: 5s
      left_ingesters_timeout: 5m
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s
      node_name: ""
      packet_dial_timeout: 5s
      packet_write_timeout: 5s
      pull_push_interval: 30s
      randomize_node_name: true
      rejoin_interval: 0s
      retransmit_factor: 2
      stream_timeout: 10s
    multitenancy_enabled: true
    overrides:
      per_tenant_override_config: /runtime-config/overrides.yaml
    querier:
      frontend_worker:
        frontend_address: gem-tempo-query-frontend-discovery:9095
      max_concurrent_queries: 20
      search:
        external_backend: null
        external_endpoints: []
        external_hedge_requests_at: 8s
        external_hedge_requests_up_to: 2
        prefer_self: 10
        query_timeout: 30s
      trace_by_id:
        query_timeout: 10s
    query_frontend:
      max_outstanding_per_tenant: 2000
      max_retries: 2
      metrics:
        concurrent_jobs: 1000
        duration_slo: 0s
        interval: 5m
        max_duration: 3h
        query_backend_after: 30m
        target_bytes_per_job: 104857600
        throughput_bytes_slo: 0
      search:
        concurrent_jobs: 1000
        target_bytes_per_job: 104857600
      trace_by_id:
        query_shards: 50
    server:
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      http_listen_port: 3100
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
      log_format: logfmt
      log_level: info
    storage:
      trace:
        backend: s3
        blocklist_poll: 5m
        local:
          path: /var/tempo/traces
        pool:
          max_workers: 400
          queue_depth: 20000
        s3:
          access_key: grafana-tempo
          bucket: enterprise-traces
          endpoint: tempo-minio:9000
          insecure: true
          secret_key: supersecret
        wal:
          path: /var/tempo/wal
    usage_report:
      reporting_enabled: true
