---
# Source: tempo-distributed/templates/ingester/service-ingester.yaml
apiVersion: v1
kind: Service
metadata:
  name: gem-tempo-ingester
  namespace: grafana-enterprise-metrics
  labels:
    helm.sh/chart: tempo-distributed-1.23.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: gem
    app.kubernetes.io/component: ingester
    app.kubernetes.io/version: "2.6.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: gem
    app.kubernetes.io/component: ingester
