apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: configmap-grafana_patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: grafana
  - path: deployment-grafana_patch.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
  - path: service-grafana_patch.json
    target:
      version: v1
      kind: Service
      name: grafana