global:
  clusterDomain: 'cluster.local'

multitenancyEnabled: true
enterprise:
  enabled: true

enterpriseGateway:
  ingress:
    enabled: true
    hosts:
      - host: stadler-get.se-demo.grafana.net
        paths:
          - path: /
            pathType: Prefix
    tls: null
    annotations:
      kubernetes.io/ingress.global-static-ip-name: stadler-get
      networking.gke.io/managed-certificates: stadler-get-cert-object
      kubernetes.io/ingress.allow-http: "false"

# MinIO storage configuration
minio:
  enabled: true
  mode: standalone
  rootUser: grafana-tempo
  rootPassword: supersecret
  buckets:
    # Bucket for traces storage if enterprise.enabled is true - requires license.
    - name: enterprise-traces
      policy: none
      purge: false
    # Admin client bucket if enterprise.enabled is true - requires license.
    - name: enterprise-traces-admin
      policy: none
      purge: false
  # Changed the mc config path to '/tmp' from '/etc' as '/etc' is only writable by root and OpenShift will not permit this.
  configPathmc: '/tmp/minio/mc/'
storage:
  trace:
    backend: s3
    s3:
      access_key: 'grafana-tempo'
      secret_key: 'supersecret'
      bucket: 'enterprise-traces'
      endpoint: 'tempo-minio:9000'
      insecure: true
  admin:
    backend: s3
    s3:
      access_key_id: 'grafana-tempo'
      secret_access_key: 'supersecret'
      bucket_name: 'enterprise-traces-admin'
      endpoint: 'tempo-minio:9000'
      insecure: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
distributor:
  config:
    log_received_spans:
      enabled: true

license:
  external: true
  secretName: 'gem-license'