---
# Source: tempo-distributed/templates/tokengen/tokengen-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: tempo-tokengen-job
  labels:
    helm.sh/chart: tempo-distributed-1.23.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: tokengen-job
    app.kubernetes.io/version: "2.6.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-install
  namespace: "grafana-enterprise-traces"
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        helm.sh/chart: tempo-distributed-1.23.2
        app.kubernetes.io/name: tempo
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/version: "2.6.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: tokengen-job
      namespace: "grafana-enterprise-traces"
    spec:
      serviceAccountName: tempo
      securityContext:
        null
      
      initContainers:
        []
      containers:
        - name: tokengen
          image: "docker.io/grafana/enterprise-traces:v2.6.1"
          imagePullPolicy: IfNotPresent
          args:
            - "-target=tokengen"
            - "-config.expand-env=true"
            - "-config.file=/conf/tempo.yaml"
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /runtime-config
              name: runtime-config
            - name: license
              mountPath: /license
          env:
          envFrom:
          securityContext:
            readOnlyRootFilesystem: true
      restartPolicy: OnFailure
      volumes:
        - name: config
          configMap:
            name: tempo-config
            items:
              - key: "tempo.yaml"
                path: "tempo.yaml"
        - name: runtime-config
          configMap:
            name: tempo-runtime
            items:
              - key: "overrides.yaml"
                path: "overrides.yaml"
        - name: license
          secret:
            secretName: tempo-license
        - name: storage
          emptyDir: {}
